---
title: "Replicando una RCT"
author: "Norman Simón Rodríguez"
date: "-Mayo 07 de 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ¿Qué es una RCT?

La sigla RCT en inglés significa *Randomised Controlled Trial*, que podemos traducir al español como *Ensayo Controlado Aleatorizado*.

## ¿En qué consiste la intervención que se evaluó?

Los investigadores (Orazio Attanasio, Arlen Guarín, Adriana Kugler, Carlos Medina, Costas Meghir) evaluaron una intervención usando un ensayo controlado aleatorizado.

Un resumen de la evaluación (en inglés) puede encontrarse [aquí](https://www.povertyactionlab.org/evaluation/vocational-training-disadvantaged-youth-colombia).

## Los datos

Los datos que usaremos en este tutorial, así como el artículo publicado y otros recursos adicionales se encuentran en este [link](https://www.aeaweb.org/articles?id=10.1257/app.3.3.188).

## El software

El programa informático que los investigadores utilizaron para hacer el estudio se llama STATA, pero nosotros usaremos una herramienta diferente, llamada R. En teoría, los resultados deben ser siempre los mismos aunque se use software diferente.